### ISSUE TITLE
Failed to load plugin 'msteams':

### ISSUE THREAD

**Issue by brogger71** [Neko-Design/sentry-msteams#1]
Hello,

I just upgraded to sentry 9.0.0 and tried to install this plugin. Unfortunately that was not successfull:

Failed to load plugin 'msteams':
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/site-packages/sentry/runner/initializer.py", line 31, in register_plugins
    plugin = ep.load()
  File "/usr/local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2331, in load
    self.require(*args, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2354, in require
    items = working_set.resolve(reqs, env, installer, extras=self.extras)
  File "/usr/local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 786, in resolve
raise VersionConflict(dist, req).with_context(dependent_req)

any ideas?

Thanks,
Michael

**Comment by Neko-Design** [comment]
Hey @brogger71,

That's unfortunate. I'll update my local Sentry to the new version and try to re-create and see what I can find. Were you installing using the requirements.txt method or manually after you'd installed Sentry?

**Comment by brogger71** [comment]
Hi Ewen,

I used the requirements.txt method.

Thanks,
Michael

Von meinem iPad gesendet

**Comment by Neko-Design** [comment]
Hey @brogger71, I've been able to recreate the issue and am working on a fix now. Should have something up and running by the weekend.

**Comment by Neko-Design** [comment]
Hey @brogger71,

Good news and bad news. Good news is this is pretty simple to fix. Bad news is it's actually something that Sentry seems to have changed in one of their dependencies. Sentry has a dependency on `redis-py-cluster` with a couple of conflicting versions, which is what's getting thrown in your logs when you try to install the plugin. The same issue is happening with a couple of other plugins including ones Sentry themselves are maintaining, which is quite confusing. See getsentry/sentry-redmine#16 for another example, with the same fix. 

To workaround this issue, add `redis-py-cluster==1.3.4` to the top of your requirements.txt file and rebuild you containers (if using docker) or re-run `pip install -r requirements.txt`. 

Let me know if this gets you back up and running and I'll add a note to the readme file in the repo so others can know as well.

**Comment by brogger71** [comment]
Hi Ewen,

Only good news :) that works just fine in my case. Thank you for the hint.

Michael

Von meinem iPad gesendet

**Comment by Neko-Design** [comment]
All good @brogger71, happy to help :)
