### ISSUE TITLE
Test plugin works but no alerts received

### ISSUE THREAD

**Issue by Slessi** [Neko-Design/sentry-msteams#13]
Hi again,

We receive events successfuly when using the "test plugin" button, but real events are never received. Created an alert rule that triggers for every single event for `msteams` but nothing comes in.

Sentry version: `9.1.2`
Python version: `2.7`

Seeing the below in logs, not sure if this is the problem. (xxxxx = omitted data)

```
Jul 29 12:56:37 lp130sentry01 sentry[446]:   File "/home/sentry/.local/lib/python2.7/site-packages/sentry/rules/actions/notify_event_service.py", line 67, in after
Jul 29 12:56:37 lp130sentry01 sentry[446]:     plugin = plugins.get(service)
Jul 29 12:56:37 lp130sentry01 sentry[446]:   File "/home/sentry/.local/lib/python2.7/site-packages/sentry/plugins/base/manager.py", line 62, in get
Jul 29 12:56:37 lp130sentry01 sentry[446]:     raise KeyError(slug)
Jul 29 12:56:37 lp130sentry01 sentry[446]: KeyError: u'msteams'
Jul 29 12:56:37 lp130sentry01 sentry[446]: 10:56:37 [ERROR] celery.worker.job: Task sentry.tasks.post_process.post_process_group[xxxxx] raised unexpected: KeyError(u'msteams',) (data={u'hostname': 'celery@lp130sentry01', u'name': 'sentry.tasks.post_process.post_process_group', u'args': '[]', u'internal': False, u'kwargs': "{'event': <Event at 0x7f55dad7f690: id=None, project_id=17L, group_id=924323L>, 'is_new_group_environment': False, 'is_new': False, 'primary_hash': '61221137e843f95799918edf12b3d399', 'is_sample': True, 'is_regression': None}", u'id': 'xxxxx'})
```

**Comment by Neko-Design** [comment]
Hey @Slessi :) Actually liisberg opened #5 to solve exactly this issue, simply restart your worker container :) 

> If you are running sentry through docker and experiencing alerts not being sent to Microsoft Teams or a KeyError-exception for "msteams" being raised - restart your worker container. This will resolve the problem.

I really should merge that...

**Comment by Slessi** [comment]
@Neko-Design not using Docker but a restart did fix this 👍
