### ISSUE TITLE
Clarification

### ISSUE THREAD

**Issue by PabloSzx** [Neko-Design/sentry-msteams#2]
Hello, just to know, it's not possible to use this plugin via https://sentry.io right?

**Comment by Neko-Design** [comment]
Hey @PabloSzx sorry for the wait, I have been out of state for work :) as far as I know you cannot install additional plugins on the Sentry SaaS offering as this is one of their features listed only on the server product. It looks like they have recently added a platform developer portal for the SaaS so I will forward this to one of the Microsoft Teams devs to look at an official integration as I suspect this will need to come from them...

Sorry we couldn’t get this working for you for now!
