### ISSUE TITLE
Error Loading in Sentry 9.0

### ISSUE THREAD

**Issue by tankerkiller125** [Neko-Design/sentry-msteams#3]
```
Jul 15 01:51:37 us-east-2 sentry[25552]: Traceback (most recent call last):
Jul 15 01:51:37 us-east-2 sentry[25552]:   File "/www/sentry/local/lib/python2.7/site-packages/sentry/runner/initializer.py", line 32, in re
Jul 15 01:51:37 us-east-2 sentry[25552]:     plugin = ep.load()
Jul 15 01:51:37 us-east-2 sentry[25552]:   File "/www/sentry/local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2434, in loa
Jul 15 01:51:37 us-east-2 sentry[25552]:     return self.resolve()
Jul 15 01:51:37 us-east-2 sentry[25552]:   File "/www/sentry/local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2440, in res
Jul 15 01:51:37 us-east-2 sentry[25552]:     module = __import__(self.module_name, fromlist=['__name__'], level=0)
Jul 15 01:51:37 us-east-2 sentry[25552]:   File "/www/sentry/local/lib/python2.7/site-packages/msteams/plugin.py", line 8, in <module>
Jul 15 01:51:37 us-east-2 sentry[25552]:     from sentry_plugins.base import CorePluginMixin
Jul 15 01:51:37 us-east-2 sentry[25552]: ImportError: No module named sentry_plugins.base
```

It would seem that this plugin no longer works in sentry 9.0

**Comment by Neko-Design** [comment]
Hey @tankerkiller125, thanks for raising the issue. Can you describe the Sentry setup you're running so I can replicate it as we did test during the migration to Sentry 9 and didn't experience this exact issue. We did have range of other issues though and it's entirely possible a new one was introduced in a new minor release :)

**Comment by tankerkiller125** [comment]
Fresh Install (Python method not docker) Ubuntu 18.04

Edit: I should note that I used the PIP install method and not the requirements.txt method to install the plugin.

**Comment by Neko-Design** [comment]
Hey @tankerkiller125, sorry for the wait. I've installed a few copies of Sentry 9 into a Ubuntu VM and was able to replicate this once when the install failed due to permissions issues. If you're running under a non-root account, can you try re-installing Sentry with the '--user' flags on the end as the module your error is referencing is part of the Sentry core modules - https://github.com/getsentry/sentry-plugins/blob/master/src/sentry_plugins/base.py

Alternatively, are you able to give the docker containers a go? They provide a really nice base to work in and a solid predictable environment with known dependencies.

**Comment by tankerkiller125** [comment]
I'm running under root (DigitalOcean VM) and unfortunately, docker is kind of out of the question because of how small the VM is the added overhead slows things down drastically.

**Comment by Neko-Design** [comment]
Hey @tankerkiller125, I've tried this again on a VM in my AWS account and was still unable to replicate the issue. Can you please try and enable one of the other plugins in your installation such as the Slack plugin and see what happens?

The import where you're seeing an error is the module that includes package installation detection that is common across both third party and Sentry provided plugins. See here for the equivalent import in the Sentry one - https://github.com/getsentry/sentry-plugins/blob/master/src/sentry_plugins/slack/__init__.py

If you're also unable to enable first-party plugins, an issue may need to be raised with Sentry to ensure something hasn't regressed in the latest release.

**Comment by tankerkiller125** [comment]
I've actually managed to get it working, I'm not entirely sure what happened but I installed the 3rd party auth first party plugin (AzureDev Ops was needed) and all the sudden MS Teams started working. So I'm not sure what exactly fixed the problem.
