### ISSUE TITLE
Stack Trace when Alert Fires

### ISSUE THREAD

**Issue by Neko-Design** [Neko-Design/sentry-msteams#4]
Received an email from Christian regarding an issue when an alert should be sent. Creating an issue to track it down :)

**Comment by Neko-Design** [comment]
Ideas so far: possibly celery related, may need a restart for celery to handle adding plugins. The way web and worker nodes inherit plugins could also be different in new release...

**Comment by liisberg** [comment]
Running sentry 9.1.2 through docker.

Plugin works fine through the "Test plugin" option, however crashes on firing alerts.

Stacktrace:
```
29/10/2019 09:28:4108:28:41 [ERROR] celery.worker.job: Task sentry.tasks.post_process.post_process_group[4577f670-190e-43c0-8921-a0d6f015df33] raised unexpected: KeyError(u'msteams',) (data={u'hostname': 'celery@sentry-worker-1', u'name': 'sentry.tasks.post_process.post_process_group', u'args': '[]', u'internal': False, u'kwargs': "{'event': <Event at 0x7fe4fc143410: id=9L, project_id=1L, group_id=2L>, 'is_new_group_environment': False, 'is_new': False, 'primary_hash': 'd9d53a32478f1bbf7d9d8ca6aac04ec6', 'is_sample': False, 'is_regression': None}", u'id': '4577f670-190e-43c0-8921-a0d6f015df33'})
29/10/2019 09:28:41Traceback (most recent call last):
29/10/2019 09:28:41  File "/usr/local/lib/python2.7/site-packages/celery/app/trace.py", line 240, in trace_task
29/10/2019 09:28:41    R = retval = fun(*args, **kwargs)
29/10/2019 09:28:41  File "/usr/local/lib/python2.7/site-packages/celery/app/trace.py", line 438, in __protected_call__
29/10/2019 09:28:41    return self.run(*args, **kwargs)
29/10/2019 09:28:41  File "/usr/local/lib/python2.7/site-packages/sentry_sdk/integrations/celery.py", line 155, in _inner
29/10/2019 09:28:41    reraise(*exc_info)
29/10/2019 09:28:41  File "/usr/local/lib/python2.7/site-packages/sentry_sdk/integrations/celery.py", line 150, in _inner
29/10/2019 09:28:41    return f(*args, **kwargs)
29/10/2019 09:28:41  File "/usr/local/lib/python2.7/site-packages/sentry/tasks/base.py", line 54, in _wrapped
29/10/2019 09:28:41    result = func(*args, **kwargs)
29/10/2019 09:28:41  File "/usr/local/lib/python2.7/site-packages/sentry/tasks/post_process.py", line 130, in post_process_group
29/10/2019 09:28:41    for callback, futures in rp.apply():
29/10/2019 09:28:41  File "/usr/local/lib/python2.7/site-packages/sentry/rules/processor.py", line 158, in apply
29/10/2019 09:28:41    self.apply_rule(rule)
29/10/2019 09:28:41  File "/usr/local/lib/python2.7/site-packages/sentry/rules/processor.py", line 146, in apply_rule
29/10/2019 09:28:41    for future in results:
29/10/2019 09:28:41  File "/usr/local/lib/python2.7/site-packages/sentry/rules/actions/notify_event_service.py", line 67, in after
29/10/2019 09:28:41    plugin = plugins.get(service)
29/10/2019 09:28:41  File "/usr/local/lib/python2.7/site-packages/sentry/plugins/base/manager.py", line 62, in get
29/10/2019 09:28:41    raise KeyError(slug)
29/10/2019 09:28:41KeyError: u'msteams'
29/10/2019 09:28:4108:28:41 [ERROR] celery.worker.job: Task sentry.tasks.post_process.post_process_group[d32fa228-5467-484b-b831-1cd3f5a31f1d] raised unexpected: KeyError(u'msteams',) (data={u'hostname': 'celery@sentry-worker-1', u'name': 'sentry.tasks.post_process.post_process_group', u'args': '[]', u'internal': False, u'kwargs': "{'event': <Event at 0x7fe4fc143390: id=10L, project_id=1L, group_id=3L>, 'is_new_group_environment': False, 'is_new': False, 'primary_hash': 'c931355cab41d6a8ebbb3a612e4cb8a6', 'is_sample': False, 'is_regression': None}", u'id': 'd32fa228-5467-484b-b831-1cd3f5a31f1d'})
```

**Comment by Neko-Design** [comment]
Hey @liisberg,

I've deployed a totally fresh copy of the latest sentry docker setup available from https://github.com/getsentry/onpremise by cloning that repo. I've then added `sentry-msteams` to the requirements.txt provided and run install.sh resulting in a vanilla Sentry setup.

Upon creating a project, enabling the MS Teams plugin and generating some events using the python SDK, I am receiving the messages in Teams and can see the below lines in the worker logs:

![image](https://user-images.githubusercontent.com/7447213/68279867-75eac200-00c8-11ea-8d91-d28d49d2a865.png)

```
worker_1     | 08:02:58 [INFO] sentry.plugins.mail: notification.digested (project_id=2L plugin=u'mail' event_id=6L group_id=5L rule_id=2L digest_key=u'mail:p:2')
worker_1     | 08:03:00 [INFO] sentry.plugins.msteams: notification.dispatched (project_id=2L plugin=u'msteams' event_id=6L group_id=5L rule_id=2L)
```

So, to troubleshoot further, can I get you to set up a fresh copy and update requirements.txt with just the msteams plugin to eliminate other variables before running the container build. Once we have a baseline install I can add some debug logs and we can track down what's causing it in your install. 

All the best,

Ewen

My Sentry Version: 9.1.2
Sentry MS Teams Version: 0.6.0

**Comment by Neko-Design** [comment]
Also probably good to test, which Sentry SDK are you using, I'll make sure to test it with that for future releases :)

**Comment by liisberg** [comment]
Hey @Neko-Design 
So it seems like the worker-container just needed a restart after enabling the plugin. 

> Ideas so far: possibly celery related, may need a restart for celery to handle adding plugins. The way web and worker nodes inherit plugins could also be different in new release...

I think this would solve any further issues should they occur.

Issue to be closed at your discretion.

**Comment by Neko-Design** [comment]
Thanks @liisberg, will close this for now. Please raise another issue if any problems pop up later. Will also add the worker restart to the troubleshooting section in the readme.
