### ISSUE TITLE
bug: 'Event' object has no attribute 'message_short'

### ISSUE THREAD

**Issue by SimonGolms** [Neko-Design/sentry-msteams#7]
# Bug Report

**Version**:
- Sentry 10 On-Premise
- sentry-msteams 0.6.0

**Current behavior:**
No messages can be sent, instead the following error message is logged: `AttributeError: 'Event' object has no attribute 'message_short'`

**Expected behavior:**
Sending messages without an error

**Steps to reproduce:**
1. clone https://github.com/getsentry/onpremise
2. add `sentry-msteams` to `sentry/requirements.txt`
3. run `./install.sh`
4. run `docker-compose up -d`
5. create new project, add and enable Microsoft Teams integration
6. add teams webhook url
7. click on `Test Plugin`
8. run `docker container logs --tail 100 sentry_onpremise_web_1` to get log entry

**Related code:**
```python
AttributeError: 'Event' object has no attribute 'message_short'
  File "sentry/api/endpoints/project_plugin_details.py", line 58, in post
    test_results = plugin.test_configuration(project)
  File "sentry/plugins/bases/notify.py", line 164, in test_configuration
    return self.notify(notification)
  File "msteams/plugin.py", line 64, in notify
    title = event.message_short.encode('utf-8')
```

**Other information:**
![image](https://user-images.githubusercontent.com/17799657/72068922-5c434200-32e6-11ea-9cc7-3c827461ba7e.png)

**Comment by Neko-Design** [comment]
Hey @SimonGolms, thanks for the detailed report! I’ll get the latest version deployed on the test machine tonight and replicate and should have a fix soon.

**Comment by SimonGolms** [comment]
That sounds good. This code change should be a quick win, cause when you fixed `message_short` the next error will be raised by `event.error()`. 

```
#plugin.py
...
title = event.title.encode('utf-8')
error_message = event.message.encode('utf-8')
```

**Comment by Neko-Design** [comment]
Hey @SimonGolms, sorry for the wait! Finally got some time to sit down and have a look, and it seems the whole event object has been updated and no-longer uses getters for anything, so I've added some exception handling to support both Sentry 8/9 and Sentry 10 and I'm please to report its working :) 

![image](https://user-images.githubusercontent.com/7447213/72672615-b4313400-3ab0-11ea-990d-1b9caa710eff.png)

Will merge this into master and publish a new package version so you should be good to go soon.

**Comment by Neko-Design** [comment]
0.7.0 has now been published to Pypi - https://pypi.org/project/sentry-msteams/
