### ISSUE TITLE
Installing plugin yields Internal Error when using "Test plugin"

### ISSUE THREAD

**Issue by instinct-vfx** [Neko-Design/sentry-msteams#9]
Heya,

i just tried adding the plugin to our sentry on premise installation. I could install fine and it shows up in the WebUI. However when i hit "Test plugin" i am getting:

```
Test Results
"There was an internal error with the Plugin, notify() got an unexpected keyword argument 'raise_exception'"
```

Any ideas or pointers would be appreciated. This was tested with sentry-msteams 0.7.0 off pypi and the latest tag on getsentry/sentry which reports 10.1.0.dev0 in the UI

**Comment by instinct-vfx** [comment]
I forced the docker image down to the 10.0.0 tag and that seemed to solve the issue. So either something in the 10.1 dev is broken, or something is changing so this would be a heads up. Sorry for the noise!

**Comment by bogdan-calapod** [comment]
It seems that the function defined [here](https://github.com/Neko-Design/sentry-msteams/blob/0f4dc318fcc5a55df64f615cd3711c076494b34c/msteams/plugin.py#L50) is called with another argument, which it doesn't expect.

Adding the `raise_exception` argument to the function fixes the issue. I'll make a PR regarding this (hopefully today).
